---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: sample-app-nginx-crt-secret
spec:
  encryptedData:
    hogehoge.crt: AgB7nVOIa/Y1T9NrIE29/UyC9nY+HVpbY+BGMmmqL40Nmzu2/VrSU4fA2IwlENw4g7M3RitKSwjyYteWndWV272r7bAjh6Nap4COu3+E2ouyVE5pzzCGdrkap21ReKvKH0Jo8+bzPUZLZW5BqDxFBUW7Xde5IHDB/E2txJMjdepDhByf3oF/anDaXofbi5krWT3e47JV44H7O/IhxdM9veEFh71+NuT14neW90ohqd89QcovQ5NvdP+2x9kso21tsjAQzDSTc3BakTKa0+I5CtZ5Drr2YyrNTb0auwix3OZSl1ePJTQLQoCe5GzVqO7XbR1CItjHHijIRe4FFEztq6bI/dJ4JmltipnpaLeTjOV2OA6JcliKLAUzfP2u8sf3kg/UESdJH0c6JGrleF+RkMpITdHojQmKFHpl4KOvFKTEKI+BVK5O1eGWlCGfndVv4POghbYDPTr2KB0wwqHMPPQO4Yer+tyJt/DrTob7h74ET3vToTMMKl2J24A9RgRaMLr/AAXkcxZyxDXQy++SJQqwrgZ9Mn0jzKL2ZGPzqaBCqtI0t5d4pXx/LJGqNrTjx51likrEfIXEbDdgXCRmFo2CaYBzZfFhMm4n2US54bl5dN7i91Lug+Xp3ygQHwAu2rKOA8A6c6ojz89i7yaepLt6La57nB/HoAV+8rzZ36tAj8Z904LBcLrkTBr822EU8WVChSlVWnJScPNDZvqDSCFdQHDNrrD8ldCubd+LDJO+uCVwjoDZFEeI0x8L4Hy+DGpt9Ag=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: sample-app-nginx-crt-secret
