apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-internal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    chart: ingress-nginx
    targetRevision: 4.9.0
    helm:
      parameters:
        - name: controller.ingressClassResource.name
          value: "nginx-internal"
        - name: controller.ingressClassResource.controllerValue
          value: "k8s.io/ingress-nginx-internal"
        - name: controller.ingressClass
          value: "nginx-internal"
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx-internal
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true