apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeseal-controller
spec:
  destination:
    name: ''
    namespace: kube-system
    server: >-
      https://kubernetes.default.svc
  source:
    repoURL: 'https://bitnami-labs.github.io/sealed-secrets'
    targetRevision: 2.14.2
    chart: sealed-secrets
    helm:
      parameters:
        - name: fullnameOverride
          value: "sealed-secrets-controller"
  sources: []
  project: default
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
