apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-traefik-ingress-route
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Ryoma0622/k8s-sample-manifest.git'
    path: k8s-manifests/Charts/sample-app-traefik-ingress-route
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sample-app-traefik-ingress
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
