apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-100
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ryoma0622/k8s-sample-manifest.git
    path: k8s-manifests/Charts/sample-app
    targetRevision: HEAD
    helm:
      parameters:
        - name: image.tag
          value: "1.0.0"
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-app-100
