apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-ingress
spec:
  project: default
  source:
    repoURL: 'https://github.com/Ryoma0622/k8s-sample-manifest.git'
    path: k8s-manifests/Charts/sample-app-ingress
    helm:
      parameters:
        - name: ingress.isProduction
          value: 'true'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sample-app-ingress
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
