apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sample-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sample-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sample-app.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              cpu: {{ .Values.deployment.app.resources.requests.cpu }}
              memory: {{ .Values.deployment.app.resources.requests.memory }}
            limits:
              cpu: {{ .Values.deployment.app.resources.limits.cpu }}
              memory: {{ .Values.deployment.app.resources.limits.memory }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.app.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.deployment.app.livenessProbe.path }}
              port: {{ .Values.deployment.app.livenessProbe.portName }}
            failureThreshold: {{ .Values.deployment.app.livenessProbe.failureThreshold }}
            periodSeconds: {{ .Values.deployment.app.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.deployment.app.readinessProbe.path }}
              port: {{ .Values.deployment.app.readinessProbe.portName }}
            failureThreshold: {{ .Values.deployment.app.readinessProbe.failureThreshold }}
            periodSeconds: {{ .Values.deployment.app.readinessProbe.periodSeconds }}
          startupProbe:
            httpGet:
              path: {{ .Values.deployment.app.startupProbe.path }}
              port: {{ .Values.deployment.app.startupProbe.portName }}
            initialDelaySeconds: {{ .Values.deployment.app.startupProbe.initialDelaySeconds }}
            failureThreshold: {{ .Values.deployment.app.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.deployment.app.startupProbe.periodSeconds }}
        - name: nginx
          image: nginx:alpine
          resources:
            requests:
              cpu: {{ .Values.deployment.web.resources.requests.cpu }}
              memory: {{ .Values.deployment.web.resources.requests.memory }}
            limits:
              cpu: {{ .Values.deployment.web.resources.limits.cpu }}
              memory: {{ .Values.deployment.web.resources.limits.memory }}
          ports:
            - name: http
              containerPort:  {{ .Values.deployment.web.port }}
              protocol: TCP
          volumeMounts:
            - name: nginx-proxy-config
              readOnly: true
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: sample-app-nginx-crt-secret
              readOnly: true
              mountPath: /etc/nginx/sample-app-nginx.crt
              subPath: hogehoge.crt
      volumes:
        - name: nginx-proxy-config
          configMap:
            name: sample-app-nginx-conf
#        - name: sample-app-nginx-crt-secret
#          secret:
#            secretName: sample-app-nginx-crt-secret
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
