apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
 name: sample-app-deployment-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v2
   kind: Deployment
   name: {{ include "sample-app.fullname" . }}
 minReplicas: {{ .Values.hpa.minReplicas }}
 maxReplicas: {{ .Values.hpa.maxReplicas }}
 targetCPUUtilizationPercentage: {{ .Values.hpa.targetCPUUtilizationPercentage }}
 targetMemoryUtilizationPercentage: {{ .Values.hpa.targetMemoryUtilizationPercentage }}
