apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sample-app-deployment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "sample-app.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: ContainerResource
    containerResource:
      name: cpu
      container: {{ .Values.hpa.metrics.containers.app.name }}
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.metrics.containers.app.cpu.averageUtilization }}
  - type: ContainerResource
    containerResource:
      name: memory
      container: {{ .Values.hpa.metrics.containers.app.name }}
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.metrics.containers.app.memory.averageUtilization }}
  - type: ContainerResource
    containerResource:
      name: cpu
      container: {{ .Values.hpa.metrics.containers.web.name }}
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.metrics.containers.web.cpu.averageUtilization }}
  - type: ContainerResource
    containerResource:
      name: memory
      container: {{ .Values.hpa.metrics.containers.web.name }}
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.metrics.containers.web.memory.averageUtilization }}

