apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: sample-app-deployment-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: sample-app-100
 minReplicas: 2
 maxReplicas: 5
 targetCPUUtilizationPercentage: 50
