---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: sample-app-nginx-crt-secret
spec:
  encryptedData:
    hogehoge.crt: AgChgxiGNlIBV6oxJyPkxLmWPHuYDyI/MImJNtXwZnGih1GLW2QyCgE2DI/Pr/bfob1kKh1bnu8+6VGN8B7eJzgoW5RuS5eU2NXS455MJAdOMq1dTd25KLFA6bK5yLWE1t4TP5Z3X8EfnobjxywEGgf/HPv5q731HqE/ATnqwK/R1fdpzziVEFMbQo2+x2tlByTCsE3SxP7tfkH8dCfbnGKNzw0X5UeYof/DRMO1IsEv3WxdE1TrnEMpGOWb32ZAG4Tmou57Gh79PdAYYX/JDSmUwu4MHsLKYpSg9hRcebr2oP5LKbqLpSVJS7G1K50aTqw16YQQvWCQoLlSkOjs8k6o1Z8mDHvwQ+9XaN/xXHOdfjjG/NPgNIuOu9x9LAeZNNU9L6gWKyQEA2Q4uxhniUgUNPRp+dOcMDhpMvE8DRqUTUiq8IDiyonoIV3/dKyroi23FQud433w6YtDOZGdomo7Ot0BH88E1cz6iOX3jVGjHvW+MwGOunXjkjn7gDD4c6yVzbi8duxcujqaaslplwF4k/giVqZe5wqAJHwJ4xZSM2dBdEi86dNR88yzacyZPxOfX9UCDe1cG63og91yiszdHMvWU21VDtw7kdKvxvQAz/qfzdnJ0lRpQT3B0E2OD0bh3OnCsK4ydNUP89jXoW/9ll2hcQih0yfrrhF+AF1idwblp+Wmls7CAi52nZJICj7+JEBZWyxMCMAIBIKzhHhwJyqwL3/r51H4IKp3CDPQEZ8m1+mS4Vj6+0zf89Fxhk+bupI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: sample-app-nginx-crt-secret
