replicaCount: 2

image:
  repository: sup0ry0jodoi/sample-api
  pullPolicy: IfNotPresent
  tag: "1.0.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 80

deployment:
  app:
    port: 8080
  nginx:
    port: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
