replicaCount: 3

image:
  repository: sup0ry0jodoi/sample-api
  pullPolicy: IfNotPresent
  tag: "1.0.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 80

deployment:
  app:
    port: 8080
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
  web:
    port: 80
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

hpa:
  minReplicas: 2
  maxReplicas: 10
  metrics:
    containers:
      app:
        name: sample-app
        cpu:
          averageUtilization: 50
        memory:
          averageUtilization: 50
      web:
        name: nginx
        cpu:
          averageUtilization: 50
        memory:
          averageUtilization: 50
