apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sample-app-traefik-ingress-route
  namespace: sample-app-100
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`sample-app-traefik-ingress.example.com`)
      kind: Rule
      services:
        - name: sample-app-100
          port: 80
