ingress:
  name: "sample-app-ingress.yaml"
  nameRc: "sample-app-ingress.yaml-rc"
  nameCanary: "sample-app-ingress.yaml-canary"
  isProduction: false
  isCanaryEnabled: false
  enabled: true
  className: "nginx"
  classNameRc: "nginx-internal"
  host: "sample-app-ingress.yaml.example.com"
  hostRc: "sample-app-ingress.yaml-rc.example.com"
  svc:
    name: "sample-app-svc"
    nameRc: "sample-app-svc-rc"
  path: "/"
  pathType: "ImplementationSpecific"
  namespace: "sample-app-ingress.yaml"
  namespaceRc: "sample-app-ingress.yaml-rc"
  annotations: {}
  port: 80
  external:
    service:
      name: "sample-app-100"
#      name: "sample-app-200"
      nameRc: "sample-app-200"
    namespace: "sample-app-100"
#    namespace: "sample-app-200"
    namespaceRc: "sample-app-200"
  tls: []
